### ISSUE TITLE
No config file example

### ISSUE THREAD

**Issue by T145** [coolsquid/LogFilters#1]
The link to the mod's documentation is dead. I would love to use this if you could post some text document describing how to configure it. A simple `README.md` at the base of this repo can do the trick.

**Comment by coolsquid** [comment]
Thanks for the report.

I have added a [`README.md`](https://github.com/coolsquid/LogFilters/blob/master/README.md) and a [configuration file example](https://github.com/coolsquid/LogFilters/blob/master/LogFilters.conf). I will update the CurseForge page shortly.
